# Generated by Django 2.2 on 2020-02-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bblocks', '0002_auto_20200209_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='returned',
        ),
    ]
